application: game
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  expiration: "1d"

- url: /.*
  script: main.py

